In [15]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [16]:
df_leetcode = pd.read_json("../leetcode_data.json")
df_leetcode.head()

,totalSolved,totalSubmissions,totalQuestions,easySolved,totalEasy,mediumSolved,totalMedium,hardSolved,totalHard,ranking,contributionPoint,reputation,submissionCalendar,recentSubmissions,matchedUserStats
0,341,"[{'difficulty': 'All', 'count': 364, 'submissi...",3451,95,857,212,1795,34,799,266340,1525,0,"{'1710028800': 2, '1711152000': 2, '1711238400...",[{'title': 'Assign Elements to Groups with Con...,"{'acSubmissionNum': [{'difficulty': 'All', 'co..."
1,46,"[{'difficulty': 'All', 'count': 51, 'submissio...",3451,18,857,28,1795,0,799,1911716,565,0,"{'1724284800': 5, '1725321600': 3, '1725753600...","[{'title': 'Product of the Last K Numbers', 't...","{'acSubmissionNum': [{'difficulty': 'All', 'co..."
2,202,"[{'difficulty': 'All', 'count': 214, 'submissi...",3451,56,857,133,1795,13,799,550057,1678,0,"{'1715990400': 1, '1716163200': 2, '1716249600...",[{'title': 'Find Valid Pair of Adjacent Digits...,"{'acSubmissionNum': [{'difficulty': 'All', 'co..."
3,624,"[{'difficulty': 'All', 'count': 669, 'submissi...",3451,191,857,334,1795,99,799,77694,3084,5,"{'1708128000': 5, '1708214400': 9, '1708819200...",[{'title': 'First Completely Painted Row or Co...,"{'acSubmissionNum': [{'difficulty': 'All', 'co..."
4,1481,"[{'difficulty': 'All', 'count': 1522, 'submiss...",3451,400,857,811,1795,270,799,3997,3673,1,"{'1707955200': 2, '1708041600': 2, '1708128000...","[{'title': 'Count Special Subsequences', 'titl...","{'acSubmissionNum': [{'difficulty': 'All', 'co..."

In [17]:
df_codeforces = pd.read_json("../codeforces_data.json")
df_codeforces.head()

,user,problem,verdict,programmingLanguage,submissionTime,problemStatistics
0,tanishqrathore_07,"{'contestId': 2067, 'index': 'A', 'name': 'Adj...",OK,C++17 (GCC 7-32),1739286285,"{'contestId': 2067, 'index': 'A', 'solvedCount..."
1,tanishqrathore_07,"{'contestId': 2067, 'index': 'A', 'name': 'Adj...",WRONG_ANSWER,C++17 (GCC 7-32),1739285886,"{'contestId': 2067, 'index': 'A', 'solvedCount..."
2,tanishqrathore_07,"{'contestId': 2065, 'index': 'B', 'name': 'Ski...",OK,C++17 (GCC 7-32),1739127898,"{'contestId': 2065, 'index': 'B', 'solvedCount..."
3,tanishqrathore_07,"{'contestId': 2065, 'index': 'C2', 'name': 'Sk...",WRONG_ANSWER,C++17 (GCC 7-32),1739120095,"{'contestId': 2065, 'index': 'C2', 'solvedCoun..."
4,tanishqrathore_07,"{'contestId': 2065, 'index': 'C1', 'name': 'Sk...",OK,C++17 (GCC 7-32),1739116649,"{'contestId': 2065, 'index': 'C1', 'solvedCoun..."